In [1]:
import torch

In [ ]:
A = torch.arange(6).reshape(3, 2)
A

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [3]:
A.T

tensor([[0, 2, 4],
        [1, 3, 5]])

In [6]:
X = torch.arange(24).reshape(2, 3, 4)
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [7]:
a = 2.0
a + X, a * X

(tensor([[[ 2.,  3.,  4.,  5.],
          [ 6.,  7.,  8.,  9.],
          [10., 11., 12., 13.]],
 
         [[14., 15., 16., 17.],
          [18., 19., 20., 21.],
          [22., 23., 24., 25.]]]),
 tensor([[[ 0.,  2.,  4.,  6.],
          [ 8., 10., 12., 14.],
          [16., 18., 20., 22.]],
 
         [[24., 26., 28., 30.],
          [32., 34., 36., 38.],
          [40., 42., 44., 46.]]]))

In [12]:
A

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [11]:
sum_A = A.sum(axis=1, keepdims=True)
sum_A, sum_A.shape

(tensor([[1],
         [5],
         [9]]),
 torch.Size([3, 1]))

In [13]:
A / sum_A

tensor([[0.0000, 1.0000],
        [0.4000, 0.6000],
        [0.4444, 0.5556]])

In [15]:
A.cumsum(axis=0), A.cumsum(axis=1)

(tensor([[0, 1],
         [2, 4],
         [6, 9]]),
 tensor([[0, 1],
         [2, 5],
         [4, 9]]))

In [22]:
x = torch.arange(3, dtype=torch.float32)
y = torch.ones(3, dtype = torch.float32)
dot = torch.dot(x,y)
x, y, dot, torch.sum(x*y)

(tensor([0., 1., 2.]), tensor([1., 1., 1.]), tensor(3.), tensor(3.))

In [25]:
A, x, A.T

(tensor([[0, 1],
         [2, 3],
         [4, 5]]),
 tensor([0., 1., 2.]),
 tensor([[0, 2, 4],
         [1, 3, 5]]))

In [29]:
A = A.float()

In [31]:
A.T @ x, torch.mv(A.T, x)

(tensor([10., 13.]), tensor([10., 13.]))

In [33]:
B = torch.ones(3,4)
A.T @ B, torch.mm(A.T, B)

(tensor([[6., 6., 6., 6.],
         [9., 9., 9., 9.]]),
 tensor([[6., 6., 6., 6.],
         [9., 9., 9., 9.]]))

In [35]:
torch.norm(x), torch.sqrt(torch.sum(x*x))

(tensor(2.2361), tensor(2.2361))

In [37]:
torch.abs(x).sum()

tensor(3.)

In [39]:
A = torch.randn(100, 200)
B = torch.randn(100, 200)
C = torch.randn(100, 200)

X = torch.stack([A, B, C], dim=2)   # shape (100, 200, 3)
B_recovered = X[:, :, 1]            # shape (100, 200)

X.shape, torch.allclose(B, B_recovered)      # True


(torch.Size([100, 200, 3]), True)

In [43]:
A = torch.randn(100, 200)
B = torch.randn(100, 200)
C = torch.randn(100, 200)

X = torch.stack([A, B, C], dim=0)   # shape (100, 200, 3)
B_recovered = X[1, :, :]            # shape (100, 200)

X.shape, torch.allclose(B, B_recovered)     # True


(torch.Size([3, 100, 200]), True)