In [97]:
%cd /Users/sauravkrishna/Documents/Python_stuffs/projects/deep_learning_ninja/d2l/d2l-en/pytorch/my_notebooks
from pathlib import Path
base_dir = Path().resolve()


/Users/sauravkrishna/Documents/Python_stuffs/projects/deep_learning_ninja/d2l/d2l-en/pytorch/my_notebooks


/opt/anaconda3/envs/d2l/lib/python3.9/site-packages/IPython/core/magics/osm.py:417: UserWarning: using dhist requires you to install the `pickleshare` library.
  self.shell.db['dhist'] = compress_dhist(dhist)[-100:]


In [98]:
base_dir

PosixPath('/Users/sauravkrishna/Documents/Python_stuffs/projects/deep_learning_ninja/d2l/d2l-en/pytorch/my_notebooks')

In [1]:
import torch

In [3]:
x = torch.arange(12, dtype = torch.float32)

In [5]:
x.numel(), len(x)

(12, 12)

In [7]:
x.shape

torch.Size([12])

In [10]:
y = x.reshape((3,4))
y

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [12]:
x.reshape(-1,4), x.reshape(3,-1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [15]:
y = torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
y

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

In [16]:
y.shape == (3,4)

True

In [17]:
type(y.shape)

torch.Size

In [18]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [20]:
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
X, Y

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor([[2., 1., 4., 3.],
         [1., 2., 3., 4.],
         [4., 3., 2., 1.]]))

In [22]:
torch.cat((X,Y), dim=0), torch.cat((X,Y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [25]:
X == Y, X< Y, X > Y

(tensor([[False,  True, False,  True],
         [False, False, False, False],
         [False, False, False, False]]),
 tensor([[ True, False,  True, False],
         [False, False, False, False],
         [False, False, False, False]]),
 tensor([[False, False, False, False],
         [ True,  True,  True,  True],
         [ True,  True,  True,  True]]))

In [26]:
X.sum(), X.mean(), X.std()

(tensor(66.), tensor(5.5000), tensor(3.6056))

In [29]:
X.sum(dim=0, keepdim = True), X.sum(dim=1)

(tensor([[12., 15., 18., 21.]]), tensor([ 6., 22., 38.]))

In [30]:
X.sum(dim=0, keepdim = True).shape, X.sum(dim=1).shape

(torch.Size([1, 4]), torch.Size([3]))

## broadcasting:  principles
1. align the two tensors, copy either of the tensors, if possible, along axis with 1 to match the other tensor, if axis misssing - insert new axis and expand
2. perform an element wise operation after matching the dimensions.
3. Along each trailing dimension, the dimension sizes must either be: (1) equal, (2) one of them is 1, or (3) one of them does not exist.


In [55]:
a = torch.arange(3).reshape((3, 1))
b = torch.linspace(1,2,2)
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([1., 2.]))

In [56]:
a + b

tensor([[1., 2.],
        [2., 3.],
        [3., 4.]])

In [57]:
a - b

tensor([[-1., -2.],
        [ 0., -1.],
        [ 1.,  0.]])

In [58]:
a * b

tensor([[0., 0.],
        [1., 2.],
        [2., 4.]])

In [59]:
a / b

tensor([[0.0000, 0.0000],
        [1.0000, 0.5000],
        [2.0000, 1.0000]])

In [60]:
a // b

tensor([[0., 0.],
        [1., 0.],
        [2., 1.]])

In [61]:
a = torch.arange(1, 6, dtype =torch.float32).reshape((5, 1))
b = torch.arange(1, 3).reshape((1, 2))
a, b

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.]]),
 tensor([[1, 2]]))

In [ ]:
a // b ## floor division

tensor([[1., 0.],
        [2., 1.],
        [3., 1.],
        [4., 2.],
        [5., 2.]])

In [64]:
a % b ## remainder

tensor([[0., 1.],
        [0., 0.],
        [0., 1.],
        [0., 0.],
        [0., 1.]])

In [65]:
Y

tensor([[ 2.,  4., 10., 12.],
        [13., 17., 21., 25.],
        [28., 30., 32., 34.]])

In [34]:
before = id(Y)
Y = Y + X
id(Y) == before

False

In [35]:
before = id(Y)
Y += X
id(Y) == before

True

In [36]:
before = id(Y)
Y[:] = Y + X
id(Y) == before

True

In [37]:
Z = torch.zeros_like(Y)
print('id(Z):', id(Z))
Z[:] = X + Y
print('id(Z):', id(Z))


id(Z): 5844071344
id(Z): 5844071344


In [38]:
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)

## Data preprocessing

In [72]:
import os

os.makedirs(os.path.join('..', 'data'), exist_ok=True)
data_file = os.path.join('..', 'data', 'house_tiny.csv')
with open(data_file, 'w') as f:
    f.write('''NumRooms,RoofType,Price
NA,NA,127500
2,NA,106000
4,Slate,178100
NA,NA,140000''')

In [73]:
import pandas as pd
data = pd.read_csv(data_file)
data

NumRooms RoofType   Price
0       NaN      NaN  127500
1       2.0      NaN  106000
2       4.0    Slate  178100
3       NaN      NaN  140000

In [74]:
data.isna()

NumRooms  RoofType  Price
0      True      True  False
1     False      True  False
2     False     False  False
3      True      True  False

In [81]:
inputs, targets = data.iloc[:, 0:2], data.iloc[:, -1]
inputs = pd.get_dummies(inputs, dummy_na=True)
inputs

NumRooms  RoofType_Slate  RoofType_nan
0       NaN           False          True
1       2.0           False          True
2       4.0            True         False
3       NaN           False          True

In [84]:
inputs = inputs.fillna(inputs.mean())
inputs

NumRooms  RoofType_Slate  RoofType_nan
0       3.0           False          True
1       2.0           False          True
2       4.0            True         False
3       3.0           False          True

In [85]:
inputs.mean()

NumRooms          3.00
RoofType_Slate    0.25
RoofType_nan      0.75
dtype: float64

In [88]:
X = torch.tensor(inputs.to_numpy(dtype = float))
y = torch.tensor(targets.to_numpy(dtype=float))
X, y

(tensor([[3., 0., 1.],
         [2., 0., 1.],
         [4., 1., 0.],
         [3., 0., 1.]], dtype=torch.float64),
 tensor([127500., 106000., 178100., 140000.], dtype=torch.float64))

In [91]:
from pathlib import Path
import IPython

In [ ]:
IPython.get_ipython().getoutput("pwd")

'/Users/sauravkrishna/Documents/Python_stuffs/projects/deep_learning_ninja'

In [99]:
base_dir

PosixPath('/Users/sauravkrishna/Documents/Python_stuffs/projects/deep_learning_ninja/d2l/d2l-en/pytorch/my_notebooks')

In [100]:
abalon_data_path = base_dir / 'abalone' / 'abalone.data'
abalon_data_path

PosixPath('/Users/sauravkrishna/Documents/Python_stuffs/projects/deep_learning_ninja/d2l/d2l-en/pytorch/my_notebooks/abalone/abalone.data')

In [114]:
cols = [
    "Sex", "Length", "Diameter", "Height",
    "Whole weight", "Shucked weight",
    "Viscera weight", "Shell weight",
    "Rings"
]

In [115]:
abalone_df = pd.read_csv(abalon_data_path, header=None, names=cols)
abalone_df

Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
0      M   0.455     0.365   0.095        0.5140          0.2245   
1      M   0.350     0.265   0.090        0.2255          0.0995   
2      F   0.530     0.420   0.135        0.6770          0.2565   
3      M   0.440     0.365   0.125        0.5160          0.2155   
4      I   0.330     0.255   0.080        0.2050          0.0895   
...   ..     ...       ...     ...           ...             ...   
4172   F   0.565     0.450   0.165        0.8870          0.3700   
4173   M   0.590     0.440   0.135        0.9660          0.4390   
4174   M   0.600     0.475   0.205        1.1760          0.5255   
4175   F   0.625     0.485   0.150        1.0945          0.5310   
4176   M   0.710     0.555   0.195        1.9485          0.9455   

      Viscera weight  Shell weight  Rings  
0             0.1010        0.1500     15  
1             0.0485        0.0700      7  
2             0.1415        0.2100      9  
3             0.1140        0.1550     10  
4             0.0395        0.0550      7  
...              ...           ...    ...  
4172          0.2390        0.2490     11  
4173          0.2145        0.2605     10  
4174          0.2875        0.3080      9  
4175          0.2610        0.2960     10  
4176          0.3765        0.4950     12  

[4177 rows x 9 columns]

In [116]:
abalone_df.isna().sum()

Sex               0
Length            0
Diameter          0
Height            0
Whole weight      0
Shucked weight    0
Viscera weight    0
Shell weight      0
Rings             0
dtype: int64

In [117]:
abalone_df.describe()

Length     Diameter       Height  Whole weight  Shucked weight  \
count  4177.000000  4177.000000  4177.000000   4177.000000     4177.000000   
mean      0.523992     0.407881     0.139516      0.828742        0.359367   
std       0.120093     0.099240     0.041827      0.490389        0.221963   
min       0.075000     0.055000     0.000000      0.002000        0.001000   
25%       0.450000     0.350000     0.115000      0.441500        0.186000   
50%       0.545000     0.425000     0.140000      0.799500        0.336000   
75%       0.615000     0.480000     0.165000      1.153000        0.502000   
max       0.815000     0.650000     1.130000      2.825500        1.488000   

       Viscera weight  Shell weight        Rings  
count     4177.000000   4177.000000  4177.000000  
mean         0.180594      0.238831     9.933684  
std          0.109614      0.139203     3.224169  
min          0.000500      0.001500     1.000000  
25%          0.093500      0.130000     8.000000  
50%          0.171000      0.234000     9.000000  
75%          0.253000      0.329000    11.000000  
max          0.760000      1.005000    29.000000

In [118]:
abalone_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4177 entries, 0 to 4176
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Sex             4177 non-null   object 
 1   Length          4177 non-null   float64
 2   Diameter        4177 non-null   float64
 3   Height          4177 non-null   float64
 4   Whole weight    4177 non-null   float64
 5   Shucked weight  4177 non-null   float64
 6   Viscera weight  4177 non-null   float64
 7   Shell weight    4177 non-null   float64
 8   Rings           4177 non-null   int64  
dtypes: float64(7), int64(1), object(1)
memory usage: 293.8+ KB


In [112]:
abalone_df.iloc[:, 0].value_counts()

0
M    1528
I    1342
F    1307
Name: count, dtype: int64

In [113]:
abalone_df.shape

(4177, 9)