In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.9.0+cpu


In [ ]:
x = torch.rand(3, 4)

In [ ]:
print(x)

tensor([[0.9844, 0.8552, 0.1004, 0.4718],
        [0.4434, 0.8952, 0.3436, 0.5343],
        [0.1036, 0.1123, 0.3358, 0.1971]])


In [ ]:
#if GPU/TPU
!nvidia-smi

# Tensor intro

In [3]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
scalar.item()

7

In [6]:
scalar.shape

torch.Size([])

In [7]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [8]:
vector.ndim

1

In [13]:
vector.shape == (2,) # 1D tensor

True

In [15]:
#MATRIX
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [16]:
MATRIX.ndim

2

In [17]:
MATRIX[0], MATRIX[1]

(tensor([7, 8]), tensor([ 9, 10]))

In [18]:
MATRIX.shape

torch.Size([2, 2])

In [21]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                       [4, 5, 6]],
                       [[7, 8, 9],
                        [10, 11, 12]]])

In [22]:
TENSOR.shape

torch.Size([2, 2, 3])

In [23]:
TENSOR = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]])

In [25]:
TENSOR.shape

torch.Size([1, 3, 3])

In [26]:
TENSOR.ndim

3

In [31]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [33]:
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.0956, 0.6449, 0.8108, 0.2186],
        [0.8054, 0.3099, 0.6481, 0.6320],
        [0.1735, 0.6994, 0.7893, 0.0255]])

In [34]:
random_tensor.ndim

2

In [35]:
random_tensor.shape

torch.Size([3, 4])

In [37]:
random_image_size_tensor = torch.rand(size=(3, 224, 224)) ## color channels, height, width: R | G | B
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [39]:
zeros_mask = torch.zeros(size=(3, 4))
zeros_mask

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [40]:
zeros_mask * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [41]:
ones_t = torch.ones(size=(3, 4))
ones_t

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [43]:
ones_t.dtype, type(ones_t)

(torch.float32, torch.Tensor)

In [51]:
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [52]:
one_to_ten.shape

torch.Size([10])

In [54]:
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [61]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                                dtype=torch.float32,
                               device="cpu",
                               requires_grad=False
                               )
print(float_32_tensor)

tensor([3., 6., 9.])


In [63]:
float_32_tensor.dtype


torch.float32

In [64]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [66]:
(float_16_tensor * float_32_tensor).dtype
#

torch.float32

In [67]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor
#

tensor([3, 6, 9], dtype=torch.int32)

In [68]:
int_32_tensor * float_16_tensor

tensor([ 9., 36., 81.], dtype=torch.float16)

In [69]:
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.5022, 0.0136, 0.6334, 0.3698],
        [0.0471, 0.5694, 0.1697, 0.1469],
        [0.2448, 0.5192, 0.6510, 0.9945]])

In [72]:
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.5022, 0.0136, 0.6334, 0.3698],
        [0.0471, 0.5694, 0.1697, 0.1469],
        [0.2448, 0.5192, 0.6510, 0.9945]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


In [71]:
some_tensor.size()

torch.Size([3, 4])

In [73]:
tensor = torch.tensor([1, 2, 3])
tensor

tensor([1, 2, 3])

In [76]:
tensor.mul(10), tensor * 10

(tensor([10, 20, 30]), tensor([10, 20, 30]))

In [78]:
print(tensor, '*', tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [80]:
torch.matmul(tensor, tensor)

tensor(14)

In [81]:
torch.dot(tensor, tensor)

tensor(14)

In [82]:
tensor @ tensor

tensor(14)

In [83]:
tensor.shape == (3,)

True

In [84]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 1.65 ms, sys: 989 µs, total: 2.64 ms
Wall time: 7.01 ms


In [85]:
%%time
value = torch.matmul(tensor, tensor)
print(value)

tensor(14)
CPU times: user 1.11 ms, sys: 960 µs, total: 2.07 ms
Wall time: 1.79 ms


In [86]:
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])


In [93]:
tensor_B

tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])

In [94]:
tensor_B.T, tensor_B.reshape(-1, 3)

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 tensor([[ 7, 10,  8],
         [11,  9, 12]]))

In [88]:
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [100]:
tensor_A.shape, tensor_A.shape[0], tensor_A.shape[-1], tensor_A.shape

(torch.Size([3, 2]), 3, 2, torch.Size([3, 2]))

In [114]:
x = torch.arange(1, 100, 10)
x, x.dtype

(tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]), torch.int64)

In [115]:
x.min(), torch.min(x), x.max(), torch.max(x)

(tensor(1), tensor(1), tensor(91), tensor(91))

In [116]:
x.type(torch.float32).mean(), torch.mean(x.type(torch.float32))

(tensor(46.), tensor(46.))

In [117]:
#x.mean()  - wont work as it needs floating point dtype tensors

In [118]:
x.sum(), torch.sum(x)

(tensor(460), tensor(460))

In [119]:
x.argmin(), torch.argmin(x), x[x.argmin()]

(tensor(0), tensor(0), tensor(1))

In [120]:
x.argmax(), torch.argmax(x), x[torch.argmax(x)]

(tensor(9), tensor(9), tensor(91))

tensor(90)


 # Reshaping, viewing, stackign, squeeze and unqueeze, permute



In [122]:
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [125]:
x_reshaped = x.reshape(len(x), -1)
x_reshaped, x_reshaped.shape


(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [126]:
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [127]:
x.view(1, 9)

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [130]:
# z shares the same memory as x: i.e the view of a tensor shares the same memory
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [133]:
x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [135]:
z.shape

torch.Size([1, 9])

In [139]:
y = torch.rand(3,4)
torch.squeeze(y)

tensor([[0.6126, 0.9750, 0.3489, 0.8404],
        [0.5606, 0.0241, 0.4161, 0.5186],
        [0.2140, 0.5346, 0.1162, 0.3713]])

In [144]:
x_reshaped

tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [148]:
x_squeezed = x_reshaped.squeeze() ## squeeze removes all single dimensions in a tensor
x_squeezed, x_squeezed.shape


(tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [153]:
## torch.unsqueeze() adds a single dimension to a target tensor at a specific dim
x_unsqueezed = x_squeezed.unsqueeze(dim=-1)
x_unsqueezed, x_unsqueezed.shape

(tensor([[5.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [154]:
## torch.permute() rearranges the dimensions of a tensor to a specific shape - returns a view
x_original = torch.rand(size=(224, 224, 3))
x_permuted = x_original.permute(2, 0, 1)
x_original.shape, x_permuted.shape

(torch.Size([224, 224, 3]), torch.Size([3, 224, 224]))

#Indexing

In [155]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [157]:
x[0], x[0].shape

(tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 torch.Size([3, 3]))

In [158]:
x[0][0], x[0, 0]

(tensor([1, 2, 3]), tensor([1, 2, 3]))

In [161]:
x[0, 0, 0], x[:, :, 0], x[:, :, -1]

(tensor(1), tensor([[1, 4, 7]]), tensor([[3, 6, 9]]))

In [162]:
x[:, :, 0], x[:, :, -1].shape

(tensor([[1, 4, 7]]), torch.Size([1, 3]))

In [163]:
x[:, 0], x[:, 0, :]

(tensor([[1, 2, 3]]), tensor([[1, 2, 3]]))

In [165]:
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [166]:
array.dtype

dtype('float64')

In [167]:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [169]:
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)

random_tensor_C = torch.rand(3, 4)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8694, 0.5677, 0.7411, 0.4294],
        [0.8854, 0.5739, 0.2666, 0.6274],
        [0.2696, 0.4414, 0.2969, 0.8317]])


In [170]:
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])


## Running on GPUs

## Getting GPUs
1. Easiest - Colab
2. get your own - expensive
3. Use clud computing - AWS / GCP / Azure - allows you to rent computers on the cloud and access them

In [1]:
!nvidia-smi

Mon Dec 15 10:46:50 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   61C    P8             13W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [3]:
import torch

In [4]:
torch.cuda.is_available()

True

## Setup device agnostic code

In [6]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [7]:
torch.cuda.device_count()

1

In [8]:
tensor = torch.tensor([1, 2, 3])
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [9]:
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [12]:
# tensor_on_gpu.numpy() - errors

In [13]:
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])